### ISSUE TITLE
ERROR:root:Unpacking GTX3 exception

### ISSUE THREAD

**Issue by hillolsarker** [muschellij2/gt3x#3]
I am getting following exception for some of my gt3x files:

ERROR:root:Unpacking GTX3 exception: cannot reshape array of size 5120 into shape (40,3)
ERROR:root:Error rescaling log data: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by muschellij2** [comment]
Please send a minimal working example or the data.

**Comment by hillolsarker** [comment]
Unfortunately due to the sensitive nature of the gt3x file I am unable to share it. Here is the stack trace:

TypeError                                 Traceback (most recent call last)
SOME_PATH/site-packages/gt3x-0.1.1-py3.6.egg/gt3x/gt3x_functions.py in rescale_log_data(log_data, acceleration_scale)
    472                 # apply scaling and return
--> 473                 return log_data * scale_factor
    474         except Exception as e:

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

During handling of the above exception, another exception occurred:

...
...
---> 15         actigraph_acc, actigraph_time, meta_data = gt3x.read_gt3x(gt3x_filepath)
...
...

SOME_PATH/site-packages/gt3x-0.1.1-py3.6.egg/gt3x/gt3x_functions.py in read_gt3x(f, save_location, create_time, rescale_data, verbose, trim)
    563 
    564         if rescale_data:
--> 565                 actigraph_acc = rescale_log_data(log_data = log_data, acceleration_scale = float(meta_data['Acceleration_Scale']))
    566         else :
    567                 actigraph_acc = log_data

SOME_PATH/site-packages/gt3x-0.1.1-py3.6.egg/gt3x/gt3x_functions.py in rescale_log_data(log_data, acceleration_scale)
    474         except Exception as e:
    475                 logging.error('Error rescaling log data: {}'.format(e))
--> 476                 exit(1)
    477 
    478 

NameError: name 'exit' is not defined

**Comment by hillolsarker** [comment]
I can understand. Here is one example file which causes similar exception:
ERROR:root:Unpacking GTX3 exception: cannot reshape array of size 10544 into shape (30,3)
ERROR:root:Error rescaling log data: unsupported operand type(s) for *: 'NoneType' and 'float'

[example_unpacking GTX3 exception.gt3x.zip](https://github.com/muschellij2/gt3x/files/8045733/example_unpacking.GTX3.exception.gt3x.zip)
